name: Josh Hart Triple Double Bot

on:
  workflow_dispatch:    # so you can run it manually

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install tweepy requests pytz balldontlie==0.1.6

      - name: Run balldontlie test
        run: python balldontlie_test.py

      - name: Run script
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          BALLEDONTLIE_API_KEY: ${{ secrets.BALLEDONTLIE_API_KEY }}
          TEST_MODE: "1"
        run: python main.py
